name: "Map Upload"
description: "Submit a new map"
title: "[Map Upload] <Map Name>"
labels: map-upload, review
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📍 **New Map Upload**
        Please fill out the following details to submit a new map upload for review.

  - type: input
    id: map_name
    attributes:
      label: "Map Name"
      description: "Provide the name of the map"
      placeholder: "Enter the map name"

  - type: input
    id: map_author
    attributes:
      label: "Map Author"
      description: "Name of the uploader or source"
      placeholder: "Enter the map author"

  - type: input
    id: collaborators
    attributes:
      label: "Collaborators (Optional)"
      description: "GitHub usernames of people who should be able to contribute to this submission (comma-separated)"
      placeholder: "e.g., @user1, @user2, @user3"
    validations:
      required: false

  - type: input
    id: map_url
    attributes:
      label: "Map File URL (Optional)"
      description: "If you have the map file hosted somewhere (e.g., Discord, Google Drive, Dropbox), provide the download link here. Otherwise, you'll upload it directly to the PR."
      placeholder: "https://example.com/mymap.map"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 📤 **How Map Upload Works**

        **Note:** GitHub issues don't support file uploads directly. Instead:

        1. ✅ Submit this issue with the information above
        2. 🤖 A pull request will be **automatically created** for you
        3. 📁 You'll upload your `.map` file to that pull request
        4. ✨ Your map will be validated and reviewed

        **Don't worry!** You'll receive detailed instructions in the PR on how to upload your map file.

  - type: markdown
    attributes:
      value: |
        ## 🚀 **What Happens Next**
        - A pull request will be automatically created
        - You and your collaborators will be able to upload files to the PR
        - The issue will be closed with a link to the PR
        - Upload your map file to the PR and wait for review
