name: "Map Upload"
description: "Submit a new map"
title: "[Map Upload] <Map Name>"
labels: map-upload, review
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📍 **New Map Upload**
        Please fill out the following details to submit a new map upload for review.

  - type: input
    id: map_name
    attributes:
      label: "Map Name"
      description: "Provide the name of the map"
      placeholder: "Enter the map name"

  - type: input
    id: map_author
    attributes:
      label: "Map Author"
      description: "Name of the uploader or source"
      placeholder: "Enter the map author"

  - type: input
    id: collaborators
    attributes:
      label: "Collaborators (Optional)"
      description: "GitHub usernames of people who should be able to contribute to this submission (comma-separated)"
      placeholder: "e.g., @user1, @user2, @user3"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## 🚀 **Action Triggers**
        - A pull request will be automatically created
        - You and your collaborators will be able to upload files to the PR
        - Instructions will be provided in the PR
