name: KoG Map Workflow
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: KoG-teeworlds/maps-workflow@v1
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
