name: KoG Map Workflow
on:
  pull_request:

jobs:
  initial:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Comment on pull request
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: "KoG-teeworlds/maps"
          number: ${{ github.event.number }}
          id: status-comment
          message: "Thank you for opening this PR, maps will now be checked... :pray:"
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get changed files
        id: changed-files
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            changed_files=$(git diff --name-only HEAD^)
          else
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          fi

          formatted_files=$(echo "$changed_files" | tr '\n' ',' | sed 's/,$//')
          echo "changed_files=$formatted_files" >> $GITHUB_OUTPUT

  evaluate:
    runs-on: ubuntu-latest
    needs: initial
    outputs:
      status: ${{ steps.maps-workflow.outputs.status }}
    continue-on-error: true
    steps:
      - name: Run maps workflow
        continue-on-error: true
        uses: KoG-teeworlds/maps-workflow@main
        id: maps-workflow
        with:
          maps: ${{ needs.initial.outputs.changed_files }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: "KoG-teeworlds/maps"
          action: check

  generate_new_votes:
    runs-on: ubuntu-latest
    needs: [initial, evaluate]
    outputs:
      status: ${{ steps.maps-workflow-generate-votes.outputs.status }}
    continue-on-error: true
    steps:
      - name: Generate new vote list
        uses: KoG-teeworlds/maps-workflow@main
        id: maps-workflow-generate-votes
        with:
          maps: ${{ needs.initial.outputs.changed_files }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: "KoG-teeworlds/maps"
          action: check_if_vote_exists

  report:
    runs-on: ubuntu-latest
    needs: [evaluate, generate_new_votes]
    if: always()
    steps:
      - name: Comment on pull request
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: "KoG-teeworlds/maps"
          number: ${{ github.event.number }}
          id: status-comment
          message: "Maps have been evaluated :pray: \n${{ needs.evaluate.outputs.status }}\n${{ needs.generate_new_votes.outputs.status}}"
          recreate: true
