name: KoG Map Workflow
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get changed files
        id: changed-files
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            changed_files=$(git diff --name-only HEAD^)
          else
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          fi

          echo "changed_files=$(echo $changed_files | tr '\n' ',')" >> $GITHUB_OUTPUT

      - name: Debug changed files
        shell: bash
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.changed_files }}"

      - name: List changed files
        uses: KoG-teeworlds/maps-workflow@v1
        with:
          maps: ${{ steps.changed-files.outputs.changed_files }}

      - name: comment on the pull request
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: "KoG-teeworlds/maps"
          number: ${{ github.event.number }}
          id: thank-you-comment
          message: "Thank you for opening this PR :pray:"
