name: KoG Map Workflow
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: KoG-teeworlds/maps-workflow@v1
      - name: comment on the pull request
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: "KoG-teeworlds/maps"
          number: ${{ github.event.number }}
          id: thank-you-comment
          message: "Thank you for opening this PR :pray:"
