name: KoG Map Workflow
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Comment on pull request
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: "KoG-teeworlds/maps"
          number: ${{ github.event.number }}
          id: status-comment
          message: "Thank you for opening this PR, maps will now be checked... :pray:"

      - name: Get changed files
        id: changed-files
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            changed_files=$(git diff --name-only HEAD^)
          else
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          fi

          formatted_files=$(echo "$changed_files" | tr '\n' ',' | sed 's/,$//')
          echo "changed_files=$formatted_files" >> $GITHUB_OUTPUT

      - name: Run maps workflow
        uses: KoG-teeworlds/maps-workflow@main
        id: maps-workflow
        with:
          maps: ${{ steps.changed-files.outputs.changed_files }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: "KoG-teeworlds/maps"

      - name: Generate new vote list
        uses: KoG-teeworlds/maps-workflow@main
        id: maps-workflow-generate-votes
        with:
          maps: ${{ steps.changed-files.outputs.changed_files }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: "KoG-teeworlds/maps"
          action: check_if_vote_exists

      - name: Comment on pull request
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: "KoG-teeworlds/maps"
          number: ${{ github.event.number }}
          id: status-comment
          message: "Maps have been evaluated :pray: \n${{ steps.maps-workflow.outputs.status }}\n${{ steps.maps-workflow-generate-votes.outputs.status}}"
          recreate: true
